#!/usr/bin/env python
import os

HOOK_FILE='.git/hooks/pre-commit'

with open(HOOK_FILE, 'w') as hook:
    hook.write('''#!/usr/bin/env sh

if [ -z "$VIRTUAL_ENV" ] ; then
    . */bin/activate
fi

python setup.py test
''')
os.chmod(HOOK_FILE, 0o755)
