name: Python application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
    - name: Setup uv
      uses: yezz123/setup-uv@v4
    - name: Install dependencies
      run: |
        uv sync --frozen
    - name: Run tests
      run: |
        uv run pytest --cov --cov-report=xml --cov-report=term-missing
