name: Python application

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install common tools
      run: pip install pytest coverage twine
    - name: Test with integrated linters and coverage
      run: |
        python setup.py test
        coverage xml
        coverage html
